
import React, { useEffect, useState } from 'react';
import { Metadata } from 'next';
import Link from 'next/link';
import { getAllPosts } from '../../services/getPosts';
import Posts from '@/components/Posts';
import PostSearch from '@/components/PostSearch';
import { usePosts } from '@/store';

export const metadata: Metadata = {
    title: 'Blog | my next test',
    description: 'Generated by create next app',
}

// **** [1] - USE WITHOUT STATE MANAGER ***** 
// "use client"
// const page = () => {

//     const [posts, setPosts] = useState<any[]>([])
//     const [loading, setLoading] = useState(true)

//     useEffect(() => {
//         getAllPosts().then(setPosts).finally(() => setLoading(false))
//     },[])
//     return (
//         <div>
//             blog
//             <PostSearch onSearch={setPosts} />
//             {loading ? (
//                 <h3>Loading...</h3>
//             ) : (
//                 <Posts posts={posts}/>
//             )}

//         </div>
//     );
// };

// export default page;


const page = () => {

    return (
        <div>
            blog
            <PostSearch/>
            <Posts />
        </div>
    );
};

export default page;