import React from 'react';
import { Metadata } from 'next';
import Link from 'next/link';
async function getData(){
    const response = await fetch('https://jsonplaceholder.typicode.com/posts', {
        next: {
            revalidate: 60
        }
    })

    if(!response.ok) throw new Error('unable to fetch posts')
    return response.json()
}

export const metadata: Metadata = {
    title: 'Blog | my next test',
    description: 'Generated by create next app',
}


const page = async () => {
    const posts = await getData()
    return (
        <div>
            blog
            <ul>
                {posts.map((post: any) => (
                    <li key={post.id}>
                        <Link href={`/blog/${post.id}`}>
                            {post.title}
                        </Link>
                    </li>
                ))}
            </ul>
        </div>
    );
};

export default page;