import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'About | my next test',
    description: 'Generated by create next app',
}

  
const page = () => {
    return (
        <div>
            choose post
        </div>
    );
};

export default page;